In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('mnist_train.csv')

In [8]:
df.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [14]:
df['1x4'].unique()

array([0], dtype=int64)

In [23]:
df.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0, 124, 253, 255,  63,   0,   0,   0,   0,
          0,   0],
       [  

In [24]:
df_x = df.iloc[:,1:].values.reshape(len(df),28,28,1)

y= df.iloc[:,0].values

In [25]:
y

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [35]:
#import keras lib
#import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Dropout
from tensorflow.keras.utils import to_categorical

In [36]:
df_y  = to_categorical(y, num_classes=10)

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(df_x,df_y, test_size=.2, random_state = 4)

In [38]:
model = Sequential()

In [39]:
model.add(Conv2D(32, kernel_size = 3, activation = 'relu', input_shape = (28,28,1)))
model.add(Flatten())
model.add(Dense(10, activation = 'softmax'))

In [41]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics=['accuracy'])

In [42]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
flatten (Flatten)            (None, 21632)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                216330    
Total params: 216,650
Trainable params: 216,650
Non-trainable params: 0
_________________________________________________________________


In [43]:
model.fit(X_train,Y_train, validation_data=(X_test,Y_test), epochs=3)

Train on 48000 samples, validate on 12000 samples
Epoch 1/3
48000/48000 [==============================] - 34s 716us/sample - loss: 1.2868 - accuracy: 0.9308 - val_loss: 0.1398 - val_accuracy: 0.9594
Epoch 2/3
48000/48000 [==============================] - 31s 655us/sample - loss: 0.0782 - accuracy: 0.9769 - val_loss: 0.1404 - val_accuracy: 0.9676
Epoch 3/3
48000/48000 [==============================] - 31s 654us/sample - loss: 0.0571 - accuracy: 0.9817 - val_loss: 0.1552 - val_accuracy: 0.9629


In [44]:
model.evaluate(X_test,Y_test)

12000/12000 [==============================] - 2s 178us/sample - loss: 0.1552 - accuracy: 0.9629


[0.15522829001808228, 0.9629167]